/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#747783",
        "on-primary-container": "#88abff",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-tertiary-fixed-variant": "#643f06",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b0c6ff",
        "tertiary-fixed-dim": "#f4bc7a",
        "surface-tint": "#315baf",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001945",
        "tertiary-fixed": "#ffddb8",
        "secondary": "#006c49",
        "inverse-surface": "#283044",
        "background": "var(--color-background)",
        "primary": "var(--color-primary)",
        "surface-dim": "#d2d9f4",
        "secondary-fixed": "#9df4c8",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b0c6ff",
        "on-secondary-fixed-variant": "#005236",
        "surface-main": "var(--color-surface-main)",
        "on-primary": "#ffffff",
        "tertiary-container": "#5d3901",
        "on-surface": "var(--color-on-surface)",
        "status-emergency": "#ba1a1a",
        "surface-container": "var(--color-surface-container)",
        "secondary-fixed-dim": "#81d8ad",
        "error": "#ba1a1a",
        "primary-fixed": "#d9e2ff",
        "on-tertiary-container": "#d8a363",
        "tertiary": "#3f2500",
        "on-primary-fixed-variant": "#0e4296",
        "telemetry-bg": "#0f172a",
        "outline-variant": "var(--color-outline-variant)",
        "error-container": "#ffdad6",
        "surface-bright": "#faf8ff",
        "surface-container-highest": "#dae2fc",
        "primary-container": "#003c90",
        "on-secondary-fixed": "#002113",
        "on-background": "var(--color-on-background)",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#0c714d",
        "surface-variant": "#dae2fc",
        "inverse-on-surface": "#eef0ff",
        "secondary-container": "#9af2c5",
        "on-tertiary-fixed": "#2a1700",
        "surface": "var(--color-surface)",
        "surface-container-high": "var(--color-surface-container-high)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "24px",
        "margin-desktop": "32px",
        "lg": "40px",
        "gutter": "24px",
        "base": "4px",
        "sm": "16px",
        "xs": "8px",
        "margin-mobile": "16px",
        "xl": "64px"
      },
      fontFamily: {
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "telemetry-mono": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "telemetry-mono": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
